# 定时任务配置
runOnStart: true
runOnSchedule: false
scheduleCron: "0 0 1 * * ?"

# 数据源配置: Map结构,key为DbName字符串,value为详细配置信息
dataSourceConfigMap: 
  mysql-ossadmin:
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.169.2.251:3306/oss6?useSSL=false
      username: ossadmin
      password: 1qaz@WSX
  oracle-ossadmin:
      driverClassName: oracle.jdbc.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@192.169.2.251:1521:orcl
      username: ossadmin
      password: ossadmin
    
# 数据移动配置: List结构
dataSyncConfigList: 

# oss关键表(20)同步: mysql --> oracle
  - {srcDbName: mysql-ossadmin, srcTableName: z010_org                  ,tarDbName: oracle-ossadmin, tarTableName: z010_org                  }  
  - {srcDbName: mysql-ossadmin, srcTableName: z010_perm                 ,tarDbName: oracle-ossadmin, tarTableName: z010_perm                 }  
  - {srcDbName: mysql-ossadmin, srcTableName: z010_resource             ,tarDbName: oracle-ossadmin, tarTableName: z010_resource             }  
  - {srcDbName: mysql-ossadmin, srcTableName: z010_role                 ,tarDbName: oracle-ossadmin, tarTableName: z010_role                 }  
  - {srcDbName: mysql-ossadmin, srcTableName: z010_user                 ,tarDbName: oracle-ossadmin, tarTableName: z010_user                 }  
  - {srcDbName: mysql-ossadmin, srcTableName: z011_role_resource        ,tarDbName: oracle-ossadmin, tarTableName: z011_role_resource        }  
  - {srcDbName: mysql-ossadmin, srcTableName: z011_user_org             ,tarDbName: oracle-ossadmin, tarTableName: z011_user_org             }  
  - {srcDbName: mysql-ossadmin, srcTableName: z011_user_perm            ,tarDbName: oracle-ossadmin, tarTableName: z011_user_perm            }  
  - {srcDbName: mysql-ossadmin, srcTableName: z011_user_role            ,tarDbName: oracle-ossadmin, tarTableName: z011_user_role            }  
  - {srcDbName: mysql-ossadmin, srcTableName: z030_job_quartz           ,tarDbName: oracle-ossadmin, tarTableName: z030_job_quartz           }  
  - {srcDbName: mysql-ossadmin, srcTableName: z030_job_rpt              ,tarDbName: oracle-ossadmin, tarTableName: z030_job_rpt              }  
  - {srcDbName: mysql-ossadmin, srcTableName: z040_notify_template      ,tarDbName: oracle-ossadmin, tarTableName: z040_notify_template      }  
  - {srcDbName: mysql-ossadmin, srcTableName: z090_db_config            ,tarDbName: oracle-ossadmin, tarTableName: z090_db_config            }  
  - {srcDbName: mysql-ossadmin, srcTableName: z090_ftp_config           ,tarDbName: oracle-ossadmin, tarTableName: z090_ftp_config           }  
  - {srcDbName: mysql-ossadmin, srcTableName: z090_report_chart_config  ,tarDbName: oracle-ossadmin, tarTableName: z090_report_chart_config  }  
  - {srcDbName: mysql-ossadmin, srcTableName: z090_report_config        ,tarDbName: oracle-ossadmin, tarTableName: z090_report_config        }  
  - {srcDbName: mysql-ossadmin, srcTableName: z090_report_field_config  ,tarDbName: oracle-ossadmin, tarTableName: z090_report_field_config  }  
  - {srcDbName: mysql-ossadmin, srcTableName: z090_report_query_config  ,tarDbName: oracle-ossadmin, tarTableName: z090_report_query_config  }  
  - {srcDbName: mysql-ossadmin, srcTableName: z090_user_config          ,tarDbName: oracle-ossadmin, tarTableName: z090_user_config          }  
  - {srcDbName: mysql-ossadmin, srcTableName: z099_code                 ,tarDbName: oracle-ossadmin, tarTableName: z099_code                 }  
